name: '🤏 Size'
on:
    pull_request:
        types: [opened, reopened, synchronize, ready_for_review]
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: 📦 Install dependencies
              run: pnpm install --frozen-lockfile

            - name: 🧪 Lint and Build
              run: pnpm lint && pnpm build

            - name: 📏 Check size
              uses: preactjs/compressed-size-action@2.5.0
              with:
                  pattern: '**/dist/**'
                  exclude: '{**/*.map,**/node_modules/**}'
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
